Repository googleapis/node-gtoken, pull requests merged in 2019-06, with the labels that each got.

#212 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
Labels: cla: yes

#213 chore: release 3.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, type: process

#214 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#215 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
Labels: cla: yes

#216 chore: release 3.0.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#217 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
