Repository googleapis/node-gtoken, pull requests merged in 2023-07, with the labels that each got.

#452 feat!: remove support for conversion of *.p12 to *.pem
  README.md
  package.json
  src/index.ts
  test/assets/key.p12
  test/index.ts
Labels: next major: breaking change, size: m

#457 chore!: move to node 14 as minimum version
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/continuous/node12/test.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node12/test.cfg
  package.json
Labels: size: m

#462 fix(deps): update gaxios to 6.0.0
  package.json
Labels: size: xs
